# Generated by New-AzureNamingStandardizationPlan.ps1 on 2026-06-17T15:14:49.2115365-04:00
# This file is intentionally non-destructive. Review, uncomment, and execute in controlled batches.
# It implements naming/region recommendations 1, 2, 3, 4, 5, 6, 8, and 9 as create/migrate/tag guidance.

# az login
# az account set --subscription '<subscription-id-or-name>'

# Create target resource group
# az group create --name 'rg-platform-shared-prod-eus2' --location 'eastus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pocouplequiz-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pocouplequizapp-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poface-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pofacedevsa-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pofunquiz-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pohappytrump-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pohappytrump2jr7zl-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poissues-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poissuestbl6824-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pojoker-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pojoker26-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-polinks-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-polinksdev01-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-polocalcompare-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-polocalcomparedevsa-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pomarriedlife-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pomarriedlifestorage-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pomemevideo-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-pominigames-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-ponovaweight-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-popunkoutersoftware-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poredoimage-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poredoimage26-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-porepolinetracker-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-porobotstocks-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-poseereview-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-potraffic-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-potrafficstorage-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-powatch-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Create target resource group
# az group create --name 'rg-powatchsa-prod-wus2' --location 'westus2' --tags env='prod' managedBy='manual-migration' namingStandard='caf-derived'

# Current: pocouplequiz / stpocouplequizapp / microsoft.storage/storageaccounts
# Target:  rg-pocouplequizapp-prod-wus2 / stpocouplequizappprodwus / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpocouplequizapp> --tags app='pocouplequizapp' env='prod' region='wus2' targetName='stpocouplequizappprodwus' namingStatus='migration-planned'

# Current: pocouplequiz / pocouplequiz-app / microsoft.web/sites
# Target:  rg-pocouplequiz-prod-wus2 / app-pocouplequiz-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-pocouplequiz-app> --tags app='pocouplequiz' env='prod' region='wus2' targetName='app-pocouplequiz-web-prod-wus2-001' namingStatus='migration-planned'

# Current: poface / pofacedevsa / microsoft.storage/storageaccounts
# Target:  rg-pofacedevsa-prod-wus2 / stpofacedevsaprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-pofacedevsa> --tags app='pofacedevsa' env='prod' region='wus2' targetName='stpofacedevsaprodwus2001' namingStatus='migration-planned'

# Current: poface / poface-dev-web / microsoft.web/sites
# Target:  rg-poface-prod-wus2 / app-poface-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-poface-dev-web> --tags app='poface' env='prod' region='wus2' targetName='app-poface-web-prod-wus2-001' namingStatus='migration-planned'

# Current: pofunquiz / storagezizogpdhpyiwo / microsoft.storage/storageaccounts
# Target:  rg-pofunquiz-prod-wus2 / stpofunquizprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-storagezizogpdhpyiwo> --tags app='pofunquiz' env='prod' region='wus2' targetName='stpofunquizprodwus2001' namingStatus='migration-planned'

# Current: pofunquiz / app-pofunquiz-zizogpdhpyiwo / microsoft.web/sites
# Target:  rg-pofunquiz-prod-wus2 / app-pofunquiz-api-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-pofunquiz-zizogpdhpyiwo> --tags app='pofunquiz' env='prod' region='wus2' targetName='app-pofunquiz-api-prod-wus2-001' namingStatus='migration-planned'

# Current: pohappytrump / stpohappytrump2jr7zl / microsoft.storage/storageaccounts
# Target:  rg-pohappytrump2jr7zl-prod-wus2 / stpohappytrump2jr7zlprod / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpohappytrump2jr7zl> --tags app='pohappytrump2jr7zl' env='prod' region='wus2' targetName='stpohappytrump2jr7zlprod' namingStatus='migration-planned'

# Current: pohappytrump / app-pohappytrump-2jr7zldry26xa / microsoft.web/sites
# Target:  rg-pohappytrump-prod-wus2 / app-pohappytrump-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-pohappytrump-2jr7zldry26xa> --tags app='pohappytrump' env='prod' region='wus2' targetName='app-pohappytrump-web-prod-wus2-001' namingStatus='migration-planned'

# Current: poissues / poissuestbl6824 / microsoft.storage/storageaccounts
# Target:  rg-poissuestbl6824-prod-wus2 / stpoissuestbl6824prodwus / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-poissuestbl6824> --tags app='poissuestbl6824' env='prod' region='wus2' targetName='stpoissuestbl6824prodwus' namingStatus='migration-planned'

# Current: poissues / po-issues / microsoft.web/sites
# Target:  rg-poissues-prod-wus2 / app-poissues-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-po-issues> --tags app='poissues' env='prod' region='wus2' targetName='app-poissues-web-prod-wus2-001' namingStatus='migration-planned'

# Current: pojoker / stpojoker26 / microsoft.storage/storageaccounts
# Target:  rg-pojoker26-prod-wus2 / stpojoker26prodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpojoker26> --tags app='pojoker26' env='prod' region='wus2' targetName='stpojoker26prodwus2001' namingStatus='migration-planned'

# Current: pojoker / app-pojoker / microsoft.web/sites
# Target:  rg-pojoker-prod-wus2 / app-pojoker-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-pojoker> --tags app='pojoker' env='prod' region='wus2' targetName='app-pojoker-web-prod-wus2-001' namingStatus='migration-planned'

# Current: polinks / stpolinksdev01 / microsoft.storage/storageaccounts
# Target:  rg-polinksdev01-prod-wus2 / stpolinksdev01prodwus200 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpolinksdev01> --tags app='polinksdev01' env='prod' region='wus2' targetName='stpolinksdev01prodwus200' namingStatus='migration-planned'

# Current: polinks / app-polinks / microsoft.web/sites
# Target:  rg-polinks-prod-wus2 / app-polinks-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-polinks> --tags app='polinks' env='prod' region='wus2' targetName='app-polinks-web-prod-wus2-001' namingStatus='migration-planned'

# Current: polocalcompare / polocalcomparedevsa / microsoft.storage/storageaccounts
# Target:  rg-polocalcomparedevsa-prod-wus2 / stpolocalcomparedevsapro / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-polocalcomparedevsa> --tags app='polocalcomparedevsa' env='prod' region='wus2' targetName='stpolocalcomparedevsapro' namingStatus='migration-planned'

# Current: polocalcompare / PoLocalCompare-AppService-dev / microsoft.web/sites
# Target:  rg-polocalcompare-prod-wus2 / app-polocalcompare-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-PoLocalCompare-AppService-dev> --tags app='polocalcompare' env='prod' region='wus2' targetName='app-polocalcompare-web-prod-wus2-001' namingStatus='migration-planned'

# Current: pomarriedlife / pomarriedlifestorage / microsoft.storage/storageaccounts
# Target:  rg-pomarriedlifestorage-prod-wus2 / stpomarriedlifestoragepr / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-pomarriedlifestorage> --tags app='pomarriedlifestorage' env='prod' region='wus2' targetName='stpomarriedlifestoragepr' namingStatus='migration-planned'

# Current: pomarriedlife / pomarriedlife-api / microsoft.web/sites
# Target:  rg-pomarriedlife-prod-wus2 / app-pomarriedlife-api-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-pomarriedlife-api> --tags app='pomarriedlife' env='prod' region='wus2' targetName='app-pomarriedlife-api-prod-wus2-001' namingStatus='migration-planned'

# Current: pomemevideo / stpomemevideo / microsoft.storage/storageaccounts
# Target:  rg-pomemevideo-prod-wus2 / stpomemevideoprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpomemevideo> --tags app='pomemevideo' env='prod' region='wus2' targetName='stpomemevideoprodwus2001' namingStatus='migration-planned'

# Current: pomemevideo / app-pomemevideo / microsoft.web/sites
# Target:  rg-pomemevideo-prod-wus2 / app-pomemevideo-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-pomemevideo> --tags app='pomemevideo' env='prod' region='wus2' targetName='app-pomemevideo-web-prod-wus2-001' namingStatus='migration-planned'

# Current: pominigames / st5ln5hfdrvof5u / microsoft.storage/storageaccounts
# Target:  rg-pominigames-prod-wus2 / stpominigamesprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-st5ln5hfdrvof5u> --tags app='pominigames' env='prod' region='wus2' targetName='stpominigamesprodwus2001' namingStatus='migration-planned'

# Current: pominigames / app-5ln5hfdrvof5u / microsoft.web/sites
# Target:  rg-pominigames-prod-wus2 / app-pominigames-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-5ln5hfdrvof5u> --tags app='pominigames' env='prod' region='wus2' targetName='app-pominigames-web-prod-wus2-001' namingStatus='migration-planned'

# Current: ponovaweight / stponovaweight / microsoft.storage/storageaccounts
# Target:  rg-ponovaweight-prod-wus2 / stponovaweightprodwus200 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stponovaweight> --tags app='ponovaweight' env='prod' region='wus2' targetName='stponovaweightprodwus200' namingStatus='migration-planned'

# Current: ponovaweight / ponovaweight-app / microsoft.web/sites
# Target:  rg-ponovaweight-prod-wus2 / app-ponovaweight-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-ponovaweight-app> --tags app='ponovaweight' env='prod' region='wus2' targetName='app-ponovaweight-web-prod-wus2-001' namingStatus='migration-planned'

# Current: popunkoutersoftware / stpopunkoutersoftware / microsoft.storage/storageaccounts
# Target:  rg-popunkoutersoftware-prod-wus2 / stpopunkoutersoftwarepro / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stpopunkoutersoftware> --tags app='popunkoutersoftware' env='prod' region='wus2' targetName='stpopunkoutersoftwarepro' namingStatus='migration-planned'

# Current: popunkoutersoftware / app-popunkoutersoftware / microsoft.web/sites
# Target:  rg-popunkoutersoftware-prod-wus2 / app-popunkoutersoftware-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-popunkoutersoftware> --tags app='popunkoutersoftware' env='prod' region='wus2' targetName='app-popunkoutersoftware-web-prod-wus2-001' namingStatus='migration-planned'

# Current: poredoimage / stporedoimage26 / microsoft.storage/storageaccounts
# Target:  rg-poredoimage26-prod-wus2 / stporedoimage26prodwus20 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stporedoimage26> --tags app='poredoimage26' env='prod' region='wus2' targetName='stporedoimage26prodwus20' namingStatus='migration-planned'

# Current: poredoimage / poredoimage-web / microsoft.web/sites
# Target:  rg-poredoimage-prod-wus2 / app-poredoimage-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-poredoimage-web> --tags app='poredoimage' env='prod' region='wus2' targetName='app-poredoimage-web-prod-wus2-001' namingStatus='migration-planned'

# Current: porepolinetracker / stporepolinetracker / microsoft.storage/storageaccounts
# Target:  rg-porepolinetracker-prod-wus2 / stporepolinetrackerprodw / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stporepolinetracker> --tags app='porepolinetracker' env='prod' region='wus2' targetName='stporepolinetrackerprodw' namingStatus='migration-planned'

# Current: porepolinetracker / app-porepolinetracker / microsoft.web/sites
# Target:  rg-porepolinetracker-prod-wus2 / app-porepolinetracker-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-porepolinetracker> --tags app='porepolinetracker' env='prod' region='wus2' targetName='app-porepolinetracker-web-prod-wus2-001' namingStatus='migration-planned'

# Current: porobotstocks / stlzwajfaczgake / microsoft.storage/storageaccounts
# Target:  rg-porobotstocks-prod-wus2 / stporobotstocksprodwus20 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stlzwajfaczgake> --tags app='porobotstocks' env='prod' region='wus2' targetName='stporobotstocksprodwus20' namingStatus='migration-planned'

# Current: porobotstocks / PoRobotStocks-PoRobotStocks-web / microsoft.web/sites
# Target:  rg-porobotstocks-prod-wus2 / app-porobotstocks-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-PoRobotStocks-PoRobotStocks-web> --tags app='porobotstocks' env='prod' region='wus2' targetName='app-porobotstocks-web-prod-wus2-001' namingStatus='migration-planned'

# Current: poseereview / stposeereview / microsoft.storage/storageaccounts
# Target:  rg-poseereview-prod-wus2 / stposeereviewprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-stposeereview> --tags app='poseereview' env='prod' region='wus2' targetName='stposeereviewprodwus2001' namingStatus='migration-planned'

# Current: poseereview / app-poseereview / microsoft.web/sites
# Target:  rg-poseereview-prod-wus2 / app-poseereview-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-poseereview> --tags app='poseereview' env='prod' region='wus2' targetName='app-poseereview-web-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / po-aiservices-shared / microsoft.cognitiveservices/accounts
# Target:  rg-platform-shared-prod-eus2 / ais-platform-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-po-aiservices-shared> --tags app='platform' env='prod' region='eus2' targetName='ais-platform-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / po-aiservices-shared/po-aiservices-shared-project / microsoft.cognitiveservices/accounts/projects
# Target:  rg-platform-shared-prod-eus2 / proj-platform-ai-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-po-aiservices-shared/po-aiservices-shared-project> --tags app='platform' env='prod' region='eus2' targetName='proj-platform-ai-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / poappideinsights8f9c9a4e / microsoft.insights/components
# Target:  rg-platform-shared-prod-eus2 / appi-platform-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-poappideinsights8f9c9a4e> --tags app='platform' env='prod' region='eus2' targetName='appi-platform-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / avail-app-porepolinetracker-health / microsoft.insights/webtests
# Target:  rg-platform-shared-prod-eus2 / avail-platform-health-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-avail-app-porepolinetracker-health> --tags app='platform' env='prod' region='eus2' targetName='avail-platform-health-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / kv-poshared / microsoft.keyvault/vaults
# Target:  rg-platform-shared-prod-eus2 / kv-platform-prod-eus2-00 / eastus2
# Action:  Create new Key Vault, migrate secrets/keys/certs metadata safely, update references, validate, then retire old vault.
# az resource tag --ids <resource-id-for-kv-poshared> --tags app='platform' env='prod' region='eus2' targetName='kv-platform-prod-eus2-00' namingStatus='migration-planned'

# Current: poshared / mi-poshared-containerapps / microsoft.managedidentity/userassignedidentities
# Target:  rg-platform-shared-prod-eus2 / id-platform-workload-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-mi-poshared-containerapps> --tags app='platform' env='prod' region='eus2' targetName='id-platform-workload-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / PoShared-LogAnalytics / microsoft.operationalinsights/workspaces
# Target:  rg-platform-shared-prod-eus2 / log-platform-ops-prod-eus2-001 / eastus2
# Action:  Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating.
# az resource tag --ids <resource-id-for-PoShared-LogAnalytics> --tags app='platform' env='prod' region='eus2' targetName='log-platform-ops-prod-eus2-001' namingStatus='migration-planned'

# Current: poshared / asp-pofunquiz-f1 / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-f1-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-pofunquiz-f1> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-f1-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / asp-pofunquiz-f2 / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-f1-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-pofunquiz-f2> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-f1-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / asp-pofunquiz-f3 / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-f1-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-pofunquiz-f3> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-f1-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / asp-poissues-b1-wus2 / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-b1-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-poissues-b1-wus2> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-b1-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / asp-poissues-f1-westus3 / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-f1-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-poissues-f1-westus3> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-f1-prod-wus2-001' namingStatus='migration-planned'

# Current: poshared / asp-poshared-linux / microsoft.web/serverfarms
# Target:  rg-platform-shared-prod-eus2 / asp-platform-linux-b2-prod-wus2-001 / westus2
# Action:  Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan.
# az resource tag --ids <resource-id-for-asp-poshared-linux> --tags app='platform' env='prod' region='wus2' targetName='asp-platform-linux-b2-prod-wus2-001' namingStatus='migration-planned'

# Current: potraffic / potrafficstorage / microsoft.storage/storageaccounts
# Target:  rg-potrafficstorage-prod-wus2 / stpotrafficstorageprodwu / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-potrafficstorage> --tags app='potrafficstorage' env='prod' region='wus2' targetName='stpotrafficstorageprodwu' namingStatus='migration-planned'

# Current: potraffic / potraffic-api / microsoft.web/sites
# Target:  rg-potraffic-prod-wus2 / app-potraffic-api-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-potraffic-api> --tags app='potraffic' env='prod' region='wus2' targetName='app-potraffic-api-prod-wus2-001' namingStatus='migration-planned'

# Current: powatch / powatchsa / microsoft.storage/storageaccounts
# Target:  rg-powatchsa-prod-wus2 / stpowatchsaprodwus2001 / westus2
# Action:  Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account.
# az resource tag --ids <resource-id-for-powatchsa> --tags app='powatchsa' env='prod' region='wus2' targetName='stpowatchsaprodwus2001' namingStatus='migration-planned'

# Current: powatch / app-powatch / microsoft.web/sites
# Target:  rg-powatch-prod-wus2 / app-powatch-web-prod-wus2-001 / westus2
# Action:  Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app.
# az resource tag --ids <resource-id-for-app-powatch> --tags app='powatch' env='prod' region='wus2' targetName='app-powatch-web-prod-wus2-001' namingStatus='migration-planned'

