#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Builds a naming and region standardization plan from azure-inventory-report.html.

.DESCRIPTION
  Reads the embedded inventory JSON generated by New-AzureEfficiencyReport.ps1 and
  writes:

  - azure-naming-standardization-plan.csv
  - azure-naming-standardization-plan.md
  - azure-naming-remediation.ps1

  The remediation script is intentionally commented out. Most Azure resource names
  cannot be changed in place, so the safe path is create, migrate, validate, cut over,
  then delete old resources.
#>

[CmdletBinding()]
param(
    [string]$ReportPath = (Join-Path (Get-Location).Path "azure-inventory-report.html"),
    [string]$OutputDirectory = (Get-Location).Path,
    [string]$DefaultEnvironment = "prod",
    [string]$PrimaryRegion = "wus2",
    [string]$PrimaryAzureLocation = "westus2",
    [string]$SharedEnvironment = "prod"
)

$ErrorActionPreference = "Stop"

function ConvertTo-Array {
    param($Value)
    if ($null -eq $Value) { return @() }
    if ($Value -is [System.Array]) { return @($Value) }
    return @($Value)
}

function Get-SkuName {
    param($Sku)
    if ($null -eq $Sku) { return "" }
    if ($Sku.PSObject.Properties.Name -contains "name") { return [string]$Sku.name }
    return [string]$Sku
}

function ConvertTo-Slug {
    param([string]$Value)
    $slug = $Value.ToLowerInvariant()
    $slug = $slug -replace "^rg-", ""
    $slug = $slug -replace "^po-", "po"
    $slug = $slug -replace "[^a-z0-9]+", "-"
    $slug = $slug.Trim("-")
    return $slug
}

function ConvertTo-StorageSegment {
    param([string]$Value)
    return (($Value.ToLowerInvariant() -replace "[^a-z0-9]", ""))
}

function Get-RegionCode {
    param([string]$Location)
    switch ($Location.ToLowerInvariant()) {
        "eastus" { return "eus" }
        "eastus2" { return "eus2" }
        "westus" { return "wus" }
        "westus2" { return "wus2" }
        "westus3" { return "wus3" }
        "centralus" { return "cus" }
        default {
            if ([string]::IsNullOrWhiteSpace($Location)) { return $PrimaryRegion }
            return ($Location.ToLowerInvariant() -replace "[^a-z0-9]", "")
        }
    }
}

function Get-ResourceAbbreviation {
    param([string]$Type)
    switch -Regex ($Type.ToLowerInvariant()) {
        "microsoft\.storage/storageaccounts" { return "st" }
        "microsoft\.web/sites" { return "app" }
        "microsoft\.web/serverfarms" { return "asp" }
        "microsoft\.keyvault/vaults" { return "kv" }
        "microsoft\.cognitiveservices/accounts/projects" { return "proj" }
        "microsoft\.cognitiveservices/accounts" { return "ais" }
        "microsoft\.insights/components" { return "appi" }
        "microsoft\.insights/webtests" { return "avail" }
        "microsoft\.managedidentity/userassignedidentities" { return "id" }
        "microsoft\.operationalinsights/workspaces" { return "log" }
        default { return "res" }
    }
}

function Get-AppFromResource {
    param($Row)
    $rg = ConvertTo-Slug $Row.ResourceGroup
    if ($rg -eq "poshared") { return "platform" }

    $name = ConvertTo-Slug $Row.Name
    foreach ($prefix in @("app-", "st", "storage", "asp-", "kv-", "id-", "appi-", "log-", "avail-")) {
        if ($name.StartsWith($prefix)) {
            $name = $name.Substring($prefix.Length)
        }
    }

    if ($name -match "^(po[a-z0-9]+)") {
        return $matches[1]
    }

    return $rg
}

function Get-Role {
    param($Row)
    $name = ConvertTo-Slug $Row.Name
    if ($Row.Type -ieq "microsoft.web/sites") {
        if ($name -match "(^|-)api($|-)") { return "api" }
        if ($name -match "(^|-)web($|-)") { return "web" }
        return "web"
    }
    if ($Row.Type -ieq "microsoft.web/serverfarms") {
        if ($name -match "linux") { return "linux" }
        return "linux"
    }
    if ($Row.Type -ieq "microsoft.insights/webtests") { return "health" }
    if ($Row.Type -ieq "microsoft.operationalinsights/workspaces") { return "ops" }
    if ($Row.Type -ieq "microsoft.managedidentity/userassignedidentities") { return "workload" }
    if ($Row.Type -ieq "microsoft.cognitiveservices/accounts") { return "shared" }
    return ""
}

function Get-TargetName {
    param($Row, [string]$App, [string]$Environment, [string]$RegionCode)

    $abbr = Get-ResourceAbbreviation $Row.Type
    $role = Get-Role $Row
    $sku = Get-SkuName $Row.Sku

    switch ($abbr) {
        "st" {
            $base = "st$(ConvertTo-StorageSegment $App)$(ConvertTo-StorageSegment $Environment)$(ConvertTo-StorageSegment $RegionCode)001"
            if ($base.Length -gt 24) { return $base.Substring(0, 24) }
            return $base
        }
        "app" {
            return "app-$App-$role-$Environment-$RegionCode-001"
        }
        "asp" {
            $skuPart = if ([string]::IsNullOrWhiteSpace($sku)) { "plan" } else { $sku.ToLowerInvariant() }
            return "asp-$App-$role-$skuPart-$Environment-$RegionCode-001"
        }
        "kv" {
            $name = "kv-$App-$Environment-$RegionCode-001"
            if ($name.Length -gt 24) { return $name.Substring(0, 24).Trim("-") }
            return $name
        }
        "ais" {
            return "ais-$App-$Environment-$RegionCode-001"
        }
        "proj" {
            return "proj-$App-ai-$Environment-$RegionCode-001"
        }
        "appi" {
            return "appi-$App-$Environment-$RegionCode-001"
        }
        "avail" {
            return "avail-$App-$role-$Environment-$RegionCode-001"
        }
        "id" {
            return "id-$App-$role-$Environment-$RegionCode-001"
        }
        "log" {
            return "log-$App-$role-$Environment-$RegionCode-001"
        }
        default {
            return "$abbr-$App-$Environment-$RegionCode-001"
        }
    }
}

function Get-Action {
    param($Row, [string]$TargetName, [string]$TargetResourceGroup, [string]$TargetLocation)

    $nameChanged = $Row.Name -cne $TargetName
    $rgChanged = $Row.ResourceGroup -cne $TargetResourceGroup
    $regionChanged = $Row.Location -cne $TargetLocation
    $caseDrift = $Row.Name -cne $Row.Name.ToLowerInvariant()

    if ($Row.Type -ieq "microsoft.web/serverfarms" -and ($nameChanged -or $rgChanged -or $regionChanged)) {
        return "Create new App Service Plan, move apps by redeploying or changing serverFarmId where compatible, validate, then remove old plan."
    }
    if ($Row.Type -ieq "microsoft.storage/storageaccounts" -and ($nameChanged -or $rgChanged -or $regionChanged)) {
        return "Create new Storage Account, copy data/configuration, update app settings and connection references, validate, then retire old account."
    }
    if ($Row.Type -ieq "microsoft.web/sites" -and ($nameChanged -or $rgChanged -or $regionChanged)) {
        return "Create new App Service, deploy app, copy configuration/custom domains, validate, then swap DNS/traffic and retire old app."
    }
    if ($Row.Type -ieq "microsoft.keyvault/vaults" -and ($nameChanged -or $rgChanged -or $regionChanged)) {
        return "Create new Key Vault, migrate secrets/keys/certs metadata safely, update references, validate, then retire old vault."
    }
    if ($nameChanged -or $rgChanged -or $regionChanged -or $caseDrift) {
        return "Recreate or redeploy with standardized name/location; use tags immediately on current resource while migrating."
    }
    return "Already conforms to proposed naming baseline; apply required tags."
}

if (-not (Test-Path $ReportPath)) {
    throw "Report not found: $ReportPath"
}

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

$html = Get-Content -Raw $ReportPath
$match = [regex]::Match($html, "const csvRows = (.*?);\s*const searchBox", [System.Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $match.Success) {
    throw "Could not find embedded csvRows inventory in $ReportPath"
}

$rows = ConvertTo-Array ($match.Groups[1].Value | ConvertFrom-Json)
$plan = foreach ($row in $rows) {
    $app = Get-AppFromResource $row
    $env = if ($row.ResourceGroup -ieq "poshared") { $SharedEnvironment } else { $DefaultEnvironment }
    $targetRg = if ($row.ResourceGroup -ieq "poshared") {
        "rg-platform-shared-$env-eus2"
    }
    else {
        "rg-$app-$env-$PrimaryRegion"
    }
    $targetLocation = if ($row.ResourceGroup -ieq "poshared" -and $row.Type -notmatch "microsoft\.web/") { "eastus2" } else { $PrimaryAzureLocation }
    $regionCode = Get-RegionCode $targetLocation
    $targetName = Get-TargetName -Row $row -App $app -Environment $env -RegionCode $regionCode

    [pscustomobject]@{
        CurrentResourceGroup = $row.ResourceGroup
        CurrentName = $row.Name
        Type = $row.Type
        CurrentLocation = $row.Location
        CurrentSku = Get-SkuName $row.Sku
        TargetResourceGroup = $targetRg
        TargetName = $targetName
        TargetLocation = $targetLocation
        App = $app
        Environment = $env
        RegionCode = $regionCode
        Action = Get-Action -Row $row -TargetName $targetName -TargetResourceGroup $targetRg -TargetLocation $targetLocation
    }
}

$csvPath = Join-Path $OutputDirectory "azure-naming-standardization-plan.csv"
$mdPath = Join-Path $OutputDirectory "azure-naming-standardization-plan.md"
$remediationPath = Join-Path $OutputDirectory "azure-naming-remediation.ps1"

$plan | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $csvPath

$markdown = [System.Collections.Generic.List[string]]::new()
$markdown.Add("# Azure Naming Standardization Plan")
$markdown.Add("")
$markdown.Add("Generated: $(Get-Date -Format o)")
$markdown.Add("")
$markdown.Add("Scope: apply recommendations 1, 2, 3, 4, 5, 6, 8, and 9 from the report review.")
$markdown.Add("")
$markdown.Add("Baseline:")
$markdown.Add("")
$markdown.Add('- Resource groups: `rg-<app>-<env>-<region>`')
$markdown.Add('- Web apps/APIs: `app-<app>-<role>-<env>-<region>-001`')
$markdown.Add('- App Service Plans: `asp-<app-or-shared>-<os>-<sku>-<env>-<region>-001`')
$markdown.Add('- Storage Accounts: `st<app><env><region>001`')
$markdown.Add('- Shared platform group: `rg-platform-shared-<env>-eus2`')
$markdown.Add("- Default workload location: $PrimaryAzureLocation / $PrimaryRegion")
$markdown.Add("")
$markdown.Add("Important: Azure resource renames are generally recreate-and-migrate operations. Do not delete old resources until apps are redeployed, data is copied, DNS/configuration is cut over, and validation passes.")
$markdown.Add("")

foreach ($group in ($plan | Group-Object CurrentResourceGroup | Sort-Object Name)) {
    $markdown.Add("## $($group.Name)")
    $markdown.Add("")
    $markdown.Add("| Current | Type | Current location | Target RG | Target name | Target location | Action |")
    $markdown.Add("|---|---|---:|---|---|---:|---|")
    foreach ($item in ($group.Group | Sort-Object Type, CurrentName)) {
        $markdown.Add("| $($item.CurrentName) | $($item.Type) | $($item.CurrentLocation) | $($item.TargetResourceGroup) | $($item.TargetName) | $($item.TargetLocation) | $($item.Action) |")
    }
    $markdown.Add("")
}

Set-Content -Path $mdPath -Value ($markdown -join [Environment]::NewLine) -Encoding UTF8

$script = [System.Collections.Generic.List[string]]::new()
$script.Add("# Generated by New-AzureNamingStandardizationPlan.ps1 on $(Get-Date -Format o)")
$script.Add("# This file is intentionally non-destructive. Review, uncomment, and execute in controlled batches.")
$script.Add("# It implements naming/region recommendations 1, 2, 3, 4, 5, 6, 8, and 9 as create/migrate/tag guidance.")
$script.Add("")
$script.Add("# az login")
$script.Add("# az account set --subscription '<subscription-id-or-name>'")
$script.Add("")

foreach ($targetRg in ($plan | Select-Object -ExpandProperty TargetResourceGroup -Unique | Sort-Object)) {
    $targetLocation = ($plan | Where-Object { $_.TargetResourceGroup -eq $targetRg } | Select-Object -First 1).TargetLocation
    $script.Add("# Create target resource group")
    $script.Add("# az group create --name '$targetRg' --location '$targetLocation' --tags env='$DefaultEnvironment' managedBy='manual-migration' namingStandard='caf-derived'")
    $script.Add("")
}

foreach ($item in ($plan | Sort-Object CurrentResourceGroup, Type, CurrentName)) {
    $script.Add("# Current: $($item.CurrentResourceGroup) / $($item.CurrentName) / $($item.Type)")
    $script.Add("# Target:  $($item.TargetResourceGroup) / $($item.TargetName) / $($item.TargetLocation)")
    $script.Add("# Action:  $($item.Action)")
    $script.Add("# az resource tag --ids <resource-id-for-$($item.CurrentName)> --tags app='$($item.App)' env='$($item.Environment)' region='$($item.RegionCode)' targetName='$($item.TargetName)' namingStatus='migration-planned'")
    $script.Add("")
}

Set-Content -Path $remediationPath -Value ($script -join [Environment]::NewLine) -Encoding UTF8

Write-Host "Naming CSV:         $csvPath" -ForegroundColor Green
Write-Host "Naming plan:        $mdPath" -ForegroundColor Green
Write-Host "Remediation script: $remediationPath" -ForegroundColor Green
