namespace PoPunkouterSoftware.Shared;

/// <summary>
/// The AI (or rule-based) triage paragraph for one scan. Precomputed once per background
/// refresh — see <c>ReportRefreshRunner</c> and <c>AiTriageService.GenerateSummaryAsync</c> in
/// Infrastructure — and attached to <see cref="AzureReport"/> before it is saved, so it
/// persists through the existing <c>AzureReportStore</c>/<c>ReportFileCache</c> paths with no
/// new storage plumbing. Also projected onto <see cref="OpsSummary"/> so the compact
/// <c>/api/diag/summary</c> first-paint contract carries it without shipping the full report
/// graph.
///
/// GoF: Value Object — immutable data carrier, no behaviour.
/// </summary>
public record AiSummaryResult
{
    /// <summary>
    /// The triage text — a model-generated paragraph, or a rule-based sentence when the AI
    /// path is disabled/unavailable. Always populated once a scan has run; never null/empty.
    /// </summary>
    public string Text { get; init; } = "";

    /// <summary>
    /// <c>"ai"</c> — freshly generated by the Hugging Face model this scan.
    /// <c>"cached"</c> — attention items were unchanged since the last scan, so the previous
    /// AI text was reused and the model call was skipped.
    /// <c>"template-fallback"</c> — the AI feature is enabled but the call failed or returned
    /// nothing, so a rule-based sentence was used instead.
    /// <c>"disabled"</c> — <c>FeatureFlags:EnableAiSummary</c> is off.
    /// </summary>
    public string Source { get; init; } = "disabled";

    /// <summary>The Hugging Face model id backing an "ai"/"cached" summary; null otherwise.</summary>
    public string? Model { get; init; }

    public DateTimeOffset GeneratedAtUtc { get; init; }

    /// <summary>
    /// SHA-256 hex digest of the attention items this summary was generated from. Lets the
    /// next scan detect "nothing attention-worthy changed" and reuse this text instead of
    /// re-calling the model.
    /// </summary>
    public string AttentionHash { get; init; } = "";
}
